// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChangePasswordInput struct {
	Token       string `json:"token"`
	NewPassword string `json:"newPassword"`
}

type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

type ForgotPasswordInput struct {
	UsernameOrEmail string `json:"usernameOrEmail"`
}

type LoginInput struct {
	UsernameOrEmail string `json:"usernameOrEmail"`
	Password        string `json:"password"`
}

type RegisterInput struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type ResetPasswordResponse struct {
	Errors     []*FieldError `json:"errors"`
	Successful *bool         `json:"successful"`
}

type UserResponse struct {
	Errors []*FieldError `json:"errors"`
	User   *User         `json:"user"`
}
